FROM python:3.11-slim

WORKDIR /app

# Instalar dependencias esenciales de compilación para psycopg2/PostgreSQL
RUN apt-get update && apt-get install -y --no-install-recommends \
    gcc \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# Crear directorios para mitigar fallos de rutas
RUN mkdir -p data/raw data/backup/raw results models

# Exponer el puerto por defecto de FastAPI
EXPOSE 8000

# Comando para arrancar Uvicorn
CMD ["uvicorn", "src.api.main:app", "--host", "0.0.0.0", "--port", "8000"]