var searchData=
[
  ['datos_0',['datos',['../md__r_e_a_d_m_e.html#autotoc_md37',1,'3. Configurar base de datos'],['../md__r_e_a_d_m_e.html#autotoc_md11',1,'Base de datos']]],
  ['datos_20en_20postgresql_1',['4. Verificar datos en PostgreSQL',['../md__r_e_a_d_m_e.html#autotoc_md24',1,'']]],
  ['de_20abandono_20de_20clientes_20en_20servicios_20de_20telecomunicaciones_2',['Modelo predictivo de riesgo de abandono de clientes en servicios de telecomunicaciones',['../md__r_e_a_d_m_e.html',1,'']]],
  ['de_20clientes_20en_20servicios_20de_20telecomunicaciones_3',['Modelo predictivo de riesgo de abandono de clientes en servicios de telecomunicaciones',['../md__r_e_a_d_m_e.html',1,'']]],
  ['de_20datos_4',['de datos',['../md__r_e_a_d_m_e.html#autotoc_md37',1,'3. Configurar base de datos'],['../md__r_e_a_d_m_e.html#autotoc_md11',1,'Base de datos']]],
  ['de_20riesgo_20de_20abandono_20de_20clientes_20en_20servicios_20de_20telecomunicaciones_5',['Modelo predictivo de riesgo de abandono de clientes en servicios de telecomunicaciones',['../md__r_e_a_d_m_e.html',1,'']]],
  ['de_20telecomunicaciones_6',['Modelo predictivo de riesgo de abandono de clientes en servicios de telecomunicaciones',['../md__r_e_a_d_m_e.html',1,'']]],
  ['de_20versiones_7',['Control de versiones',['../md__r_e_a_d_m_e.html#autotoc_md13',1,'']]],
  ['del_20pipeline_8',['Flujo del pipeline',['../md__r_e_a_d_m_e.html#autotoc_md45',1,'']]],
  ['del_20proyecto_9',['Estructura del proyecto',['../md__r_e_a_d_m_e.html#autotoc_md4',1,'']]],
  ['del_20proyecto_20expand_10',['Estructura del proyecto (expand)',['../md__r_e_a_d_m_e.html#autotoc_md58',1,'']]],
  ['dependencias_11',['2. Instalar dependencias',['../md__r_e_a_d_m_e.html#autotoc_md35',1,'']]],
  ['descripción_12',['Descripción',['../md__r_e_a_d_m_e.html#autotoc_md2',1,'']]],
  ['despliegue_13',['Despliegue',['../md__r_e_a_d_m_e.html#autotoc_md43',1,'']]],
  ['detener_20servicios_14',['5. Detener servicios',['../md__r_e_a_d_m_e.html#autotoc_md26',1,'']]],
  ['detiene_20contenedor_20volúmenes_15',['7. Elimina y detiene contenedor,volúmenes',['../md__r_e_a_d_m_e.html#autotoc_md28',1,'']]],
  ['docker_16',['Ejecución sin Docker',['../md__r_e_a_d_m_e.html#autotoc_md30',1,'']]],
  ['docker_17',['Requisitos sin docker',['../md__r_e_a_d_m_e.html#autotoc_md31',1,'']]],
  ['docker_20recomendado_18',['Ejecución con Docker (Recomendado)',['../md__r_e_a_d_m_e.html#autotoc_md15',1,'']]],
  ['docstring_19',['Documento Docstring',['../md__r_e_a_d_m_e.html#autotoc_md56',1,'']]],
  ['documento_20docstring_20',['Documento Docstring',['../md__r_e_a_d_m_e.html#autotoc_md56',1,'']]],
  ['documento_20técnico_21',['Documento técnico',['../md__r_e_a_d_m_e.html#autotoc_md55',1,'']]]
];
