create table cliente (
   customerid       varchar(50) primary key,
   gender           varchar(50),
   seniorcitizen    int,
   partner          varchar(50),
   dependents       varchar(50),
   tenure           int,
   phoneservice     varchar(50),
   multiplelines    varchar(50),
   internetservice  varchar(50),
   onlinesecurity   varchar(50),
   onlinebackup     varchar(50),
   deviceprotection varchar(50),
   techsupport      varchar(50),
   streamingtv      varchar(50),
   streamingmovies  varchar(50),
   contract         varchar(50),
   paperlessbilling varchar(50),
   paymentmethod    varchar(50),
   monthlycharges   float,
   totalcharges     varchar(50),
   churn            varchar(20)
);