create table cliente (
   customer_id      varchar(50) primary key,
   gender           varchar(10),
   seniorcitizen    int,
   partner          varchar(3),
   dependents       varchar(3),
   tenure           int,
   phoneservice     varchar(3),
   multiplelines    varchar(20),
   internetservice  varchar(20),
   onlinesecurity   varchar(25),
   onlinebackup     varchar(25),
   deviceprotection varchar(25),
   techsupport      varchar(25),
   streamingtv      varchar(25),
   streamingmovies  varchar(25),
   contract         varchar(20),
   paperlessbilling varchar(3),
   paymentmethod    varchar(40),
   monthlycharges   numeric(10,2),
   totalcharges     numeric(10,2),
   churn            varchar(3)
);