FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# Exponer el puerto por defecto de Streamlit en Render
EXPOSE 10000

# Comando para arrancar Streamlit
CMD ["streamlit", "run", "src/app.py", "--server.port", "10000", "--server.address", "0.0.0.0"]